### ISSUE TITLE
Error while running PING

### ISSUE THREAD

**Issue by patidarr** [Hollenbach-lab/PING-legacy#1]
Hi,

I tried running the pipeline and getting following error:
> ping_run_all(sample.location="/projects/Clinomics/DATA/Sample_CL0080_T1D_E2_HW7J3BGXY/", fastq.pattern.1="_R1.fastq.gz", fastq.pattern.2="_R2.fastq.gz",bowtie.threads=10,results.directory="/projects/scratch/PING/")
----- Getting PING_grabber ready -----

PING_sequences/ directory created.

Found sequences:
Sample_CL0080_T1D_E2_HW7J3BGXY

Running MrGrabWaller on: Sample_CL0080_T1D_E2_HW7J3BGXY

bowtie2 -p10 --trim5 3 --trim3 7 -L 20 -i S,1,0.5 --score-min L,0,-0.187 -I 75 -X 1000 -x Resources/grabber_resources/Filters/mrG/output -1 /projects/Clinomics/DATA/Sample_CL0080_T1D_E2_HW7J3BGXY/Sample_CL0080_T1D_E2_HW7J3BGXY_R1.fastq.gz -2 /projects/Clinomics/DATA/Sample_CL0080_T1D_E2_HW7J3BGXY/Sample_CL0080_T1D_E2_HW7J3BGXY_R2.fastq.gz -S Sample_CL0080_T1D_E2_HW7J3BGXY.temp --al-conc-gz PING_sequences/Sample_CL0080_T1D_E2_HW7J3BGXY_KIR_%.fastq.gz --un dump.me(ERR): Could not open output file 'Sample_CL0080_T1D_E2_HW7J3BGXY.temp' for writing.
Exiting now ...

on the system I am running the pipeline I am a user and don't have write permission on the location PING is installed to.

**Comment by jillahjillah** [comment]
Hi,

I'm sorry, but it is necessary to be able to write files in order to run the pipeline.

Best,

Jill

________________________________

**Comment by wesleymarin** [comment]
Hello, sorry we had to take this down to finish up the code and publication first. All of the files needed to run the code should be included in the final release.
