### ISSUE TITLE
success with exome sequencing?

### ISSUE THREAD

**Issue by timodonnell** [Hollenbach-lab/PING-legacy#3]
I'm wondering if you or others have had success running PING from whole exome sequencing? Do the probes tend to capture enough KIR region reads or do they mostly get missed?

**Comment by n0rmski** [comment]
Dear Tim
    I believe I may have been working (quite extensively) with your
      data for the last few months through Amir. 
    
    Yes there is enough data captured and it will most likely work.
      The problem is that the exome capture method was designed using
      one reference genome.
    I think this means ultimately that the coverage is not even -some
      alleles will produce more sequence reads than other alleles that
      are divergent from the reference.
    The main consequence of this so far is on the gene content
      calling, because we use relative read depth to call the gene
      content/copy number.
    
    The solution will be to run some controls -ie samples with known
      KIR alleles- through the exome capture method and then through the
      pipeline.
    As with any experiment, without controls there remains an element
      of guesswork.
    I hope this helps to clarify. Maybe we should talk directly if
      you need any further info or discussion.
    
    All the best
    Paul
    
    
    On 21-Aug-18 9:40 AM, timodonnell
      wrote:
    
    
      
      I'm wondering if you or others have had success running PING
        from whole exome sequencing? Do the probes tend to capture
        enough KIR region reads or do they mostly get missed?
      —
        You are receiving this because you are subscribed to this
        thread.
        Reply to this email directly, view it on GitHub, or mute the thread.
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Hollenbach-lab/PING","title":"Hollenbach-lab/PING","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/Hollenbach-lab/PING"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"success with exome sequencing? (#3)"}],"action":{"name":"View Issue","url":"https://github.com/Hollenbach-lab/PING/issues/3"}}}
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Hollenbach-lab/PING/issues/3",
"url": "https://github.com/Hollenbach-lab/PING/issues/3",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "success with exome sequencing? (#3)",
"sections": [
{
"text": "",
"activityTitle": "**Tim O'Donnell**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@timodonnell",
"facts": [
{
"name": "Repository: ",
"value": "Hollenbach-lab/PING"
},
{
"name": "Issue #: ",
"value": 3
}
]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"Hollenbach-lab/PING\",\n\"issueId\": 3,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"Hollenbach-lab/PING\",\n\"issueId\": 3\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/Hollenbach-lab/PING/issues/3"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 370684219\n}"
}
],
"themeColor": "26292E"
}
]
    
    
    -- 
Paul J Norman, PhD
Associate Professor
Division of Personalized Medicine,
and Department of Immunology.
Anschutz Medical School
University of Colorado

**Comment by timodonnell** [comment]
Got it, this is very helpful. Thanks, Paul. We'll think some more and be in touch if we start to try these analyses.

Best,

Tim
