### ISSUE TITLE
"Use of uninitiazed value ..." message in ping_run_all()

### ISSUE THREAD

**Issue by droeatumn** [Hollenbach-lab/PING-legacy#5]
When I run ping_run_all() on the attached paired end files after changing the first few lines of PING_run_all.R
```
  sample.location = "input/",
  fastq.pattern.1 = "_R1_001.fastq.gz",
  fastq.pattern.2 = "_R2_001.fastq.gz",
  bowtie.threads = 7,
  results.directory = "output/"
```
I get
```
----- Getting PING_grabber ready -----

PING_sequences/ directory created.

Found sequences: 
test1


Running MrGrabWaller on: test1 

bowtie2 -p7 --trim5 3 --trim3 7 -L 20 -i S,1,0.5 --score-min L,0,-0.187 -I 75 -X 1000 -x Resources/grabber_resources/Filters/mrG/output -1 input/test1_R1_001.fastq.gz -2 input/test1_R2_001.fastq.gz -S test1.temp --al-conc-gz PING_sequences/test1_KIR_%.fastq.gz --un dump.meUse of uninitialized value $bt2_args[17] in join or string at /usr/local/bin/bowtie2 line 423.
Use of uninitialized value $bt2_args[18] in join or string at /usr/local/bin/bowtie2 line 423.
Use of uninitialized value in exists at /usr/local/bin/bowtie2 line 81.
Use of uninitialized value in exists at /usr/local/bin/bowtie2 line 81.
Use of uninitialized value $bt2_args[17] in join or string at /usr/local/bin/bowtie2 line 459.
Use of uninitialized value $bt2_args[18] in join or string at /usr/local/bin/bowtie2 line 459.
20000 reads; of these:
  20000 (100.00%) were paired; of these:
    1056 (5.28%) aligned concordantly 0 times
    15 (0.07%) aligned concordantly exactly 1 time
    18929 (94.64%) aligned concordantly >1 times
    ----
    1056 pairs aligned concordantly 0 times; of these:
      0 (0.00%) aligned discordantly 1 time
    ----
    1056 pairs aligned 0 times concordantly or discordantly; of these:
      2112 mates make up the pairs; of these:
        2080 (98.48%) aligned 0 times
        0 (0.00%) aligned exactly 1 time
        32 (1.52%) aligned >1 times
94.80% overall alignment rate


MrGrabwaller is complete. Extracted reads are deposited in the PING_sequences folder.
fastq.patterns have been adjusted to _KIR_1.fastq(.gz) and _KIR_2.fastq(.gz).
----- Getting PING ready -----

Results being saved to output/ 

Found sequences: 
test1_KIR

Setting results directory to output/

----- Running KFF -----

Building primer table. 

Counting primers in: 
test1_KIR_1
Taking input= as a system command ('zcat PING_sequences/test1_KIR_1.fastq.gz') and a variable has been used in the expression passed to `input=`. Please use fread(cmd=...). There is a security concern if you are creating an app, and the app could have a malicious user, and the app is not running in a secure environment; e.g. the app is running as root. Please read item 5 in the NEWS file for v1.11.6 for more information and for the option to suppress this message.
zcat: can't stat: PING_sequences/test1_KIR_1.fastq.gz (PING_sequences/test1_KIR_1.fastq.gz.Z): No such file or directory
Error: subscript out of bounds
In addition: Warning messages:
1: In dir.create(save_to) : 'output' already exists
2: In dir.create(save_to) : 'output' already exists
3: In fread(paste("zcat", inFile), sep = "\n", nrows = read.cap, header = FALSE) :
  File '/var/folders/35/dkcf9qv55hn3sfhvvstf1yy80000gn/T//RtmpDMH95n/file9bd0557acc4d' has size 0. Returning a NULL data.table.
```

Any suggestions? I am running the latest code on OSX 10.15.4. The file 'PING_sequences/test1_KIR_1.fastq.gz' does exist.

[test1_R1_001.fastq.gz](https://github.com/Hollenbach-lab/PING/files/4534328/test1_R1_001.fastq.gz)
[test1_R2_001.fastq.gz](https://github.com/Hollenbach-lab/PING/files/4534322/test1_R2_001.fastq.gz)

**Comment by jillahjillah** [comment]
This is an outdated and unsupported version of PING. A new version, PING2, will be available soon.
Jill

On Apr 25, 2020, at 4:15 PM, Dave Roe <notifications@github.com<mailto:notifications@github.com>> wrote:


test1_R2_001.fastq.gz<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_Hollenbach-2Dlab_PING_files_4534322_test1-5FR2-5F001.fastq.gz&d=DwMCaQ&c=iORugZls2LlYyCAZRB3XLg&r=e2IGn3wB5BHyGjuDNieKjsba-4DFW1-gx_FbIMOErfY&m=ZH_3RsVkHYl0fGnixbvloj2qrSsgY-ZsMsNeJ43j-xg&s=xHKeyluuWCLP9477zI4bWQqlWzIvKs94qYKo3b4u1_4&e=>
When I run ping_run_all() on the attached paired end files after changing the first few lines of PING_run_all.R

  sample.location = "input/",
  fastq.pattern.1 = "_R1_001.fastq.gz",
  fastq.pattern.2 = "_R2_001.fastq.gz",
  bowtie.threads = 7,
  results.directory = "output/"


I get

----- Getting PING_grabber ready -----

PING_sequences/ directory created.

Found sequences:
test1


Running MrGrabWaller on: test1

bowtie2 -p7 --trim5 3 --trim3 7 -L 20 -i S,1,0.5 --score-min L,0,-0.187 -I 75 -X 1000 -x Resources/grabber_resources/Filters/mrG/output -1 input/test1_R1_001.fastq.gz -2 input/test1_R2_001.fastq.gz -S test1.temp --al-conc-gz PING_sequences/test1_KIR_%.fastq.gz --un dump.meUse of uninitialized value $bt2_args[17] in join or string at /usr/local/bin/bowtie2 line 423.
Use of uninitialized value $bt2_args[18] in join or string at /usr/local/bin/bowtie2 line 423.
Use of uninitialized value in exists at /usr/local/bin/bowtie2 line 81.
Use of uninitialized value in exists at /usr/local/bin/bowtie2 line 81.
Use of uninitialized value $bt2_args[17] in join or string at /usr/local/bin/bowtie2 line 459.
Use of uninitialized value $bt2_args[18] in join or string at /usr/local/bin/bowtie2 line 459.
20000 reads; of these:
  20000 (100.00%) were paired; of these:
    1056 (5.28%) aligned concordantly 0 times
    15 (0.07%) aligned concordantly exactly 1 time
    18929 (94.64%) aligned concordantly >1 times
    ----
    1056 pairs aligned concordantly 0 times; of these:
      0 (0.00%) aligned discordantly 1 time
    ----
    1056 pairs aligned 0 times concordantly or discordantly; of these:
      2112 mates make up the pairs; of these:
        2080 (98.48%) aligned 0 times
        0 (0.00%) aligned exactly 1 time
        32 (1.52%) aligned >1 times
94.80% overall alignment rate


MrGrabwaller is complete. Extracted reads are deposited in the PING_sequences folder.
fastq.patterns have been adjusted to _KIR_1.fastq(.gz) and _KIR_2.fastq(.gz).
----- Getting PING ready -----

Results being saved to output/

Found sequences:
test1_KIR

Setting results directory to output/

----- Running KFF -----

Building primer table.

Counting primers in:
test1_KIR_1
Taking input= as a system command ('zcat PING_sequences/test1_KIR_1.fastq.gz') and a variable has been used in the expression passed to `input=`. Please use fread(cmd=...). There is a security concern if you are creating an app, and the app could have a malicious user, and the app is not running in a secure environment; e.g. the app is running as root. Please read item 5 in the NEWS file for v1.11.6 for more information and for the option to suppress this message.
zcat: can't stat: PING_sequences/test1_KIR_1.fastq.gz (PING_sequences/test1_KIR_1.fastq.gz.Z): No such file or directory
Error: subscript out of bounds
In addition: Warning messages:
1: In dir.create(save_to) : 'output' already exists
2: In dir.create(save_to) : 'output' already exists
3: In fread(paste("zcat", inFile), sep = "\n", nrows = read.cap, header = FALSE) :
  File '/var/folders/35/dkcf9qv55hn3sfhvvstf1yy80000gn/T//RtmpDMH95n/file9bd0557acc4d' has size 0. Returning a NULL data.table.


Any suggestions? I am running the latest code on OSX 10.15.4.

test1_R1_001.fastq.gz<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_Hollenbach-2Dlab_PING_files_4534328_test1-5FR1-5F001.fastq.gz&d=DwMCaQ&c=iORugZls2LlYyCAZRB3XLg&r=e2IGn3wB5BHyGjuDNieKjsba-4DFW1-gx_FbIMOErfY&m=ZH_3RsVkHYl0fGnixbvloj2qrSsgY-ZsMsNeJ43j-xg&s=gWR5BPUcFJayvzXPAwIfSv2sp2XtP-t8wl3JRCevUeg&e=>

**Comment by droeatumn** [comment]
Thanks.
